# Generated by Django 5.2.5 on 2025-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
