# Generated by Django 5.2.5 on 2025-09-01 16:23

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_profissional_nome_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['nome'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (11)99999-9999', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')]),
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['nome'], name='profissiona_nome_7072d7_idx'),
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['especialidade'], name='profissiona_especia_c543eb_idx'),
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['email'], name='profissiona_email_69c769_idx'),
        ),
    ]
