# Generated by Django 5.0.7 on 2024-07-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMedico', models.CharField(max_length=255)),
                ('nomeSocialMedico', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=100)),
                ('enderecoMedico', models.CharField(max_length=255)),
                ('idadeMedico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePaciente', models.CharField(max_length=255)),
                ('nomeSocialPaciente', models.CharField(max_length=255)),
                ('enderecoPaciente', models.CharField(max_length=255)),
                ('idadePaciente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataConsulta', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.paciente')),
            ],
        ),
    ]
