# Generated by Django 5.0.7 on 2024-07-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='enderecoMedico',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='idadeMedico',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nomeMedico',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nomeSocialMedico',
            new_name='nomeSocial',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='enderecoPaciente',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='idadePaciente',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nomePaciente',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nomeSocialPaciente',
            new_name='nomeSocial',
        ),
    ]
