# Generated by Django 5.0.7 on 2024-07-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_nome_medico_nomecompleto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade',
            new_name='profissao',
        ),
    ]
