# Generated by Django 5.0.7 on 2024-07-28 01:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_rename_especialidade_medico_profissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
